# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4X74TUIc_qtEsSEgWQUwJDs34FCGnZd

**Matplotlib**

**Numpy**

**Dictionary**
"""

student={"name":"Farwa","Age":22,"Grade":"A"}
print(student)
student["Age"] = 23         # updates Age
student["Grade"] = "A+"     # updates Grade
print(student)

"""**List**"""

numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers)
#Sum
#print('Sum:', sum(numbers))
#Max
print('Max:', max(numbers))
#Min
print('Min:', min(numbers))
#Add and remove
numbers.append(50)
numbers.remove(4)
print('Updated list',numbers)
#Sorting in ascending and desecnding
print('Ascending Order ',sorted(numbers))
print('Descending Order ',sorted(numbers,reverse=True))

"""**Tuple**"""

fruits=("Apple","Banana","Grapes","Orange","Pomegranate")
print(fruits)
print('Second Fruit: ',fruits[1])
print('Last Fruit: ',fruits[-1])
#convert tuple to list (no modification in tuple)
# convert_to_list=list(fruits)
# convert_to_list[3]="Apricot"
# print('Modified List',convert_to_list)

"""**Set**"""

set1={1,2,3,4,5}
set2={5,6,7,8,9}
#union intersection
print('Union',set1 | set2)
print('Intersection',set1 & set2)
print('Difference',set1 - set2)
# add remove
set1.add(12)
set2.remove(8)
print(set1)
print(set2)